<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DynamicIsland.Core\DynamicIsland.Core.csproj" />
    <ProjectReference Include="..\DynamicIsland.Infrastructure\DynamicIsland.Infrastructure.csproj" />
    <ProjectReference Include="..\DynamicIsland.Platform.Windows\DynamicIsland.Platform.Windows.csproj" />
    <ProjectReference Include="..\DynamicIsland.UI\DynamicIsland.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
